name: GitHub Pacman Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Pacman Animations
        uses: Platane/pacman@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-pacman.svg
            dist/github-pacman-dark.svg?palette=github-dark
            dist/ocean.gif?color_pacman=yellow&color_dots=#f0db4f,#ffe873,#ffdd57,#ffc947,#ffb347
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update pacman animation [skip ci]"
